### ISSUE TITLE
배포환경구성하기

### ISSUE THREAD

**Issue by NESOY** [snack-news/Snack-admin#1]
- 배포 Script 작성
- Nginx 설정
- Node 배포 관리 툴
	- PM2
- 전체적인 배포 프로세스 이해하기

## Reference
- <https://github.com/snack-news/Snack-FE/tree/master/deploy>

**Comment by MartinYounghoonKim** [comment]
어드민의 경우, 클라이언트와 별도의 배포 프로세스를 가지고 있기 때문에 해당 이슈는 종료하도록 하겠습니다.
