### ISSUE TITLE
API 확인 사항

### ISSUE THREAD

**Issue by MartinYounghoonKim** [snack-news/Snack-admin#2]
- 뉴스 생성시
  - endDate 역할은 무엇인지 확인 필요
  - String 타입이 빈 값일 경우, validate 함수 오류

**Comment by Delf-Lee** [comment]
### endDate
- startDateTime과 endDateTime은 각각 뉴스 조회 시, 검색 조건에 해당하는 인자입니다
   - 현재 news에 관련된 DTO(VO)는 하나로 통합하여 운용하고 있으며, admin API에서는 해당 인자를 사용하지 않습니다.
   - 뉴스 생성용, 또는 Admin 전용 DTO를 따로 만들 여지는 있으나 추가 상의가 필요해 보입니다.

### String 타입
- String 타입이 무엇인지 파악이 힘듭니다.

**Comment by MartinYounghoonKim** [comment]
해당 내용은 상세하게 정리된 후 다시 오픈하도록 하겠습니다.
